### ISSUE TITLE
fregeNativeGen fails with frege > 3.22.367

### ISSUE THREAD

**Issue by mperry** [mperry/frege-gradle-example#7]

**Comment by mperry** [comment]
See the pure-frege submodule:

Successfully started process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe''
Exception in thread "main" java.lang.NoClassDefFoundError: frege/prelude/PreludeArrays$?$Justâ5dcd44
ac
        at frege.nativegen.java.Lang$2.eval(Lang.java:1043)
        at frege.nativegen.java.Lang$2.eval(Lang.java:1036)
        at frege.runtime.Fun1$1.eval(Fun1.java:63)
        at frege.runtime.Delayed.call(Delayed.java:198)
        at frege.runtime.Delayed.forced(Delayed.java:267)
        at frege.nativegen.Main$TKnownTypesParser$2.eval(Main.java:336)
        at frege.nativegen.Main$TKnownTypesParser$2.eval(Main.java:334)
        at frege.runtime.Fun1$1.eval(Fun1.java:63)
        at frege.runtime.Delayed.call(Delayed.java:198)
        at frege.runtime.Delayed.forced(Delayed.java:257)
        at frege.prelude.PreludeBase$TST$1.eval(PreludeBase.java:13761)
        at frege.runtime.Fun1$1.eval(Fun1.java:63)
        at frege.runtime.Delayed.call(Delayed.java:198)
        at frege.runtime.Delayed.forced(Delayed.java:257)
        at frege.prelude.PreludeBase$TST$1.eval(PreludeBase.java:13761)
        at frege.runtime.Fun1$1.eval(Fun1.java:63)
        at frege.runtime.Delayed.call(Delayed.java:200)
        at frege.runtime.Delayed.forced(Delayed.java:257)
        at frege.prelude.PreludeBase$TST$1.eval(PreludeBase.java:13761)
        at frege.runtime.Fun1$1.eval(Fun1.java:63)
        at frege.runtime.Delayed.call(Delayed.java:200)
        at frege.runtime.Delayed.forced(Delayed.java:267)
        at frege.nativegen.Main$TKnownTypesParser$1.eval(Main.java:293)
        at frege.nativegen.Main$TKnownTypesParser$1.eval(Main.java:281)
        at frege.runtime.Fun1$1.eval(Fun1.java:63)
        at frege.runtime.Delayed.call(Delayed.java:198)
        at frege.runtime.Delayed.forced(Delayed.java:267)
        at frege.nativegen.Main$2.eval(Main.java:519)
        at frege.runtime.Fun1$1.eval(Fun1.java:63)
        at frege.runtime.Delayed.call(Delayed.java:198)
        at frege.runtime.Runtime.runMain(Runtime.java:273)
        at frege.nativegen.Main.main(Main.java:700)
Caused by: java.lang.ClassNotFoundException: frege.prelude.PreludeArrays$?$Justâ5dcd44ac
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 32 more
:pure-frege:fregeNativeGen FAILED
:pure-frege:fregeNativeGen (Thread[Daemon worker Thread 2,5,main]) completed. Took 1.331 secs.

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':pure-frege:fregeNativeGen'.
  
  > Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit val
  > ue 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

**Comment by mperry** [comment]
I am guess the native gen component needs to use a newer version of frege.
